[package]
name = "pipeline_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower = "0.4.13"

[dev-dependencies]
futures = "0.3.25"
pin-utils = "0.1.0"
